version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survey_form
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    container_name: express_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: survey_form
      DB_PORT: 5432
      NODE_ENV: production
    ports:
      - "5000:5000"

  migrate:
    build:
      context: ./backend
      dockerfile: DockerFile
    working_dir: /app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: survey_form
      DB_PORT: 5432
      NODE_ENV: production
    command: sh -c "sequelize db:migrate && sequelize db:seed:all"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: next_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
      NODE_ENV: production
    ports:
      - "3000:3000"

volumes:
  postgres_data:
